// Constants for Promotion Actions

export const ALL_PROMOTIONS_REQUEST = 'ALL_PROMOTIONS_REQUEST';
export const ALL_PROMOTIONS_SUCCESS = 'ALL_PROMOTIONS_SUCCESS';
export const ALL_PROMOTIONS_FAIL = 'ALL_PROMOTIONS_FAIL';

export const NEW_PROMOTION_REQUEST = 'NEW_PROMOTION_REQUEST';
export const NEW_PROMOTION_SUCCESS = 'NEW_PROMOTION_SUCCESS';
export const NEW_PROMOTION_FAIL = 'NEW_PROMOTION_FAIL';
export const NEW_PROMOTION_RESET = 'NEW_PROMOTION_RESET';

export const DELETE_PROMOTION_REQUEST = 'DELETE_PROMOTION_REQUEST';
export const DELETE_PROMOTION_SUCCESS = 'DELETE_PROMOTION_SUCCESS';
export const DELETE_PROMOTION_FAIL = 'DELETE_PROMOTION_FAIL';
export const DELETE_PROMOTION_RESET = 'DELETE_PROMOTION_RESET';

export const UPDATE_PROMOTION_REQUEST = 'UPDATE_PROMOTION_REQUEST';
export const UPDATE_PROMOTION_SUCCESS = 'UPDATE_PROMOTION_SUCCESS';
export const UPDATE_PROMOTION_FAIL = 'UPDATE_PROMOTION_FAIL';
export const UPDATE_PROMOTION_RESET = 'UPDATE_PROMOTION_RESET';

export const PROMOTION_DETAILS_REQUEST = 'PROMOTION_DETAILS_REQUEST';
export const PROMOTION_DETAILS_SUCCESS = 'PROMOTION_DETAILS_SUCCESS';
export const PROMOTION_DETAILS_FAIL = 'PROMOTION_DETAILS_FAIL';
export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST';
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS';
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
